@echo off
set "BASE_DIR=D:\project_management_ai"

:: Create main directories
mkdir "%BASE_DIR%\backend"
mkdir "%BASE_DIR%\backend\config"
mkdir "%BASE_DIR%\backend\config\settings"
mkdir "%BASE_DIR%\backend\apps"
mkdir "%BASE_DIR%\backend\apps\core"
mkdir "%BASE_DIR%\backend\apps\projects"
mkdir "%BASE_DIR%\backend\apps\ai_module"
mkdir "%BASE_DIR%\backend\apps\risk_analysis"
mkdir "%BASE_DIR%\backend\apps\kpi"
mkdir "%BASE_DIR%\backend\apps\collaboration"
mkdir "%BASE_DIR%\backend\apps\compliance"
mkdir "%BASE_DIR%\backend\services"
mkdir "%BASE_DIR%\backend\static"
mkdir "%BASE_DIR%\backend\media"
mkdir "%BASE_DIR%\backend\templates"
mkdir "%BASE_DIR%\backend\requirements"
mkdir "%BASE_DIR%\frontend"
mkdir "%BASE_DIR%\frontend\public"
mkdir "%BASE_DIR%\frontend\src"
mkdir "%BASE_DIR%\frontend\src\apps"
mkdir "%BASE_DIR%\frontend\src\apps\dashboard"
mkdir "%BASE_DIR%\frontend\src\apps\projects"
mkdir "%BASE_DIR%\frontend\src\apps\ai_assistant"
mkdir "%BASE_DIR%\frontend\src\components"
mkdir "%BASE_DIR%\frontend\src\hooks"
mkdir "%BASE_DIR%\frontend\src\store"
mkdir "%BASE_DIR%\frontend\src\utils"
mkdir "%BASE_DIR%\ml_models"
mkdir "%BASE_DIR%\ml_models\risk_prediction"
mkdir "%BASE_DIR%\ml_models\kpi_analysis"
mkdir "%BASE_DIR%\infrastructure"
mkdir "%BASE_DIR%\infrastructure\docker"
mkdir "%BASE_DIR%\infrastructure\nginx"
mkdir "%BASE_DIR%\tests"
mkdir "%BASE_DIR%\tests\unit"
mkdir "%BASE_DIR%\tests\integration"
mkdir "%BASE_DIR%\tests\e2e"
mkdir "%BASE_DIR%\docs"

:: Create empty files
copy NUL "%BASE_DIR%\backend\config\__init__.py"
copy NUL "%BASE_DIR%\backend\config\settings\base.py"
copy NUL "%BASE_DIR%\backend\config\settings\development.py"
copy NUL "%BASE_DIR%\backend\config\settings\production.py"
copy NUL "%BASE_DIR%\backend\config\urls.py"
copy NUL "%BASE_DIR%\backend\config\wsgi.py"
copy NUL "%BASE_DIR%\backend\apps\core\__init__.py"
copy NUL "%BASE_DIR%\backend\apps\core\models.py"
copy NUL "%BASE_DIR%\backend\apps\core\utils.py"
copy NUL "%BASE_DIR%\backend\services\ai_services.py"
copy NUL "%BASE_DIR%\backend\services\risk_calculation.py"
copy NUL "%BASE_DIR%\backend\services\pmi_validator.py"
copy NUL "%BASE_DIR%\backend\requirements\base.txt"
copy NUL "%BASE_DIR%\backend\requirements\development.txt"
copy NUL "%BASE_DIR%\backend\requirements\production.txt"
copy NUL "%BASE_DIR%\backend\manage.py"
copy NUL "%BASE_DIR%\backend\.env"
copy NUL "%BASE_DIR%\frontend\package.json"
copy NUL "%BASE_DIR%\frontend\vite.config.js"
copy NUL "%BASE_DIR%\frontend\src\App.jsx"
copy NUL "%BASE_DIR%\frontend\src\main.jsx"
copy NUL "%BASE_DIR%\ml_models\risk_prediction\model.pkl"
copy NUL "%BASE_DIR%\ml_models\risk_prediction\preprocessing.py"
copy NUL "%BASE_DIR%\ml_models\kpi_analysis\model.h5"
copy NUL "%BASE_DIR%\ml_models\kpi_analysis\analyzer.py"
copy NUL "%BASE_DIR%\infrastructure\docker\django.Dockerfile"
copy NUL "%BASE_DIR%\infrastructure\docker\react.Dockerfile"
copy NUL "%BASE_DIR%\infrastructure\nginx\nginx.conf"
copy NUL "%BASE_DIR%\.gitignore"
copy NUL "%BASE_DIR%\docker-compose.yml"
copy NUL "%BASE_DIR%\Makefile"
copy NUL "%BASE_DIR%\README.md"
copy NUL "%BASE_DIR%\docs\architecture.md"
copy NUL "%BASE_DIR%\docs\api_spec.yaml"

echo Folder structure created successfully!
